### ISSUE TITLE
RIXSCAM device not working after update on startup file

### ISSUE THREAD

**Issue by bisogni** [NSLS-II-SIX/profile_collection#12]
The latest version of 22-rixscam.py start up file causes the camera not to work, neither in the regular mode nor in centroiding. Help would be needed to be able to fix this problem and test further the camera. Below, a copy/paste of the error message that appears in bluesky.

''''
In [6]: RE(bpp.pchain(count([rixscam], md={'reason':'dummy'}),count([rixscam], md={'reason':'dummy CeCoIn5 882e '})))
Transient Scan ID: 23492     Time: 2018/08/11 17:22:16
Persistent Unique Scan ID: '3eab9ca7-160a-451e-82ac-92666fbdbb50'
New stream: 'baseline'
Start-of-run baseline readings:
+--------------------------------+--------------------------------+
|                      ring_curr | 49.5950247487206               |
|                gc_tcg_pressure | 0.001                          |
|              epu1_gap_readback | 28.6947                        |
|            epu1_phase_readback | 28.4999                        |
|              feslt_hc_readback | 0.14983999999999986            |
|              feslt_vc_readback | -0.20005000000000006           |
|              feslt_hg_readback | 1.9997600000000004             |
|              feslt_vg_readback | 1.99994                        |
|                           m1_x | 0.6258                         |
|                         m1_pit | 1939.8242                      |
|                         m1_rol | 4114.738                       |
|                        pgm_cff | 2.24                           |
|                         pgm_en | 882.9993000000001              |
|                        pgm_grx | -63.0                          |
|                      pgm_m2pit | 88.2648474668197               |
|                      pgm_grpit | 87.60060350534411              |
|                       m3slt_hg | -5.323300000000001             |
|                       m3slt_hc | -3.6611000000000002            |
|                       m3slt_vg | 0.0                            |
|                       m3slt_vc | -0.0006000000000000001         |
|                       m3slt_hs | -0.9994900000000001            |
|                       m3slt_ha | -5.32368125                    |
|                       m3slt_vs | -0.000635                      |
|                       m3slt_va | 0.0                            |
|                       m3diag_y | -1.002903125                   |
|                           m3_x | 1.0                            |
|                           m3_y | 0.0                            |
|                           m3_z | 1.0                            |
|                         m3_yaw | -0.5                           |
|                         m3_pit | -0.749615                      |
|                         m3_rol | 0.14500000000000002            |
|                      extslt_hg | 150.00490000000002             |
|                      extslt_vg | 19.999000000000002             |
|                      extslt_hc | -4.1063                        |
|                       gcdiag_y | -95.40001875                   |
|                       m4_diag1 | -0.9999265625                  |
|                       m4slt_hg | -9.52                          |
|                       m4slt_hc | 5.5600000000000005             |
|                       m4slt_vg | -13.0302                       |
|                       m4slt_vc | -2.045                         |
|                      m4slt_inb | 10.32                          |
|                      m4slt_out | 0.8                            |
|                      m4slt_bot | 4.4701                         |
|                      m4slt_top | -8.5601                        |
|                           m4_x | 3.2                            |
|                           m4_y | 96.87500000000001              |
|                           m4_z | -5.4                           |
|                         m4_yaw | -1.203                         |
|                         m4_pit | -4.056                         |
|                         m4_rol | 2.552                          |
|                         cryo_x | 26.220000000000255             |
|                         cryo_y | 66.49500000000012              |
|                         cryo_z | 19.17995000000019              |
|                         cryo_t | 19.999567733800006             |
|           stemp_ctrl1_readback | 200.0                          |
|           stemp_ctrl2_readback | 200.0                          |
|                             ow | -58.327412319939995            |
|                           m5_x | -3.95                          |
|                           m5_y | 0.0                            |
|                           m5_z | 2.0                            |
|                         m5_yaw | 0.0                            |
|                         m5_pit | -9170.0                        |
|                         m5_rol | 330.0                          |
|                       m5mask_y | 21.0                           |
|                         m6_msk | 89.0                           |
|                           m6_z | 116.29003500000002             |
|                         m6_pit | 1.4092918298                   |
|                      espgm_cff | 0.0                            |
|                       espgm_en | 0.0                            |
|                    espgm_m7pit | 4.835709371                    |
|                    espgm_grpit | 4.87060580392                  |
|                    espgmmask_y | 0.0                            |
|                           oc_y | -1.1440000000000001            |
|                           oc_z | 5.058499999999981              |
|                        oc_roll | 0.006                          |
|                       oc_twoth | 91.00554708300001              |
|                        oc_wlin | -1.1459999999999582            |
|                        oc_wlot | -1.142949999999928             |
|                       dcslt_hg | 63.001000000000005             |
|                       dcslt_hc | 13.499                         |
|                       dcslt_vg | 21.001                         |
|                       dcslt_vc | -0.501                         |
|                      dcslt_inb | 18.002000000000002             |
|                      dcslt_out | 45.0                           |
|                      dcslt_bot | 11.002000000000002             |
|                      dcslt_top | 9.999999999999996              |
|                           dc_z | 180.00095000000002             |
|                       dc_twoth | 90.49784350750001              |
+--------------------------------+--------------------------------+
                                                                                                                                                                                                   

---------------------------------------------------------------------------
IllegalMessageSequence                    Traceback (most recent call last)
<ipython-input-6-a947c86f116f> in <module>()
----> 1 RE(bpp.pchain(count([rixscam], md={'reason':'dummy'}),count([rixscam], md={'reason':'dummy CeCoIn5 882e '})))

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    742                     # it (unless it is a canceled error)
    743                     if exc is not None:
--> 744                         raise exc
    745 
    746             if self._interrupted:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1251             self.log.error("Run aborted")
   1252             self.log.error("%r", err)
-> 1253             raise err
   1254         finally:
   1255             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1138                     else:
   1139                         try:
-> 1140                             msg = self._plan_stack[-1].send(resp)
   1141                         # We have exhausted the top generator
   1142                         except StopIteration:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1261         plan = monitor_during_wrapper(plan, self.monitors)
   1262         plan = baseline_wrapper(plan, self.baseline)
-> 1263         return (yield from plan)

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1116         return (yield from plan)
   1117     else:
-> 1118         return (yield from plan_mutator(plan, insert_baseline))
   1119 
   1120 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    757     plan1 = plan_mutator(plan, insert_after_open)
    758     plan2 = plan_mutator(plan1, insert_before_close)
--> 759     return (yield from plan2)
    760 
    761 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    815     plan1 = plan_mutator(plan, insert_after_open)
    816     plan2 = plan_mutator(plan1, insert_before_close)
--> 817     return (yield from plan2)
    818 
    819 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in pchain(*args)
    234     rets = deque()
    235     for p in args:
--> 236         rets.append((yield from p))
    237     return tuple(rets)
    238 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plans.py in count(detectors, num, delay, md)
     65                                       num=num, delay=delay))
     66 
---> 67     return (yield from inner_count())
     68 
     69 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1011                 plan = gen_func(*inner_args, **inner_kwargs)
   1012                 plan = wrapper(plan, *args, **kwargs)
-> 1013                 return (yield from plan)
   1014             return dec_inner
   1015         return dec

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    906         return (yield from plan)
    907 
--> 908     return (yield from finalize_wrapper(inner(), unstage_devices()))
    909 
    910 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    467     cleanup = True
    468     try:
--> 469         ret = yield from plan
    470     except GeneratorExit:
    471         cleanup = False

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in inner()
    904     def inner():
    905         yield from stage_devices()
--> 906         return (yield from plan)
    907 
    908     return (yield from finalize_wrapper(inner(), unstage_devices()))

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1011                 plan = gen_func(*inner_args, **inner_kwargs)
   1012                 plan = wrapper(plan, *args, **kwargs)
-> 1013                 return (yield from plan)
   1014             return dec_inner
   1015         return dec

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in run_wrapper(plan, md)
    293     yield from contingency_wrapper(plan,
    294                                    except_plan=except_plan,
--> 295                                    else_plan=close_run)
    296     return rs_uid
    297 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in contingency_wrapper(plan, except_plan, else_plan, final_plan, pause_for_debug)
    539             # it might be better to throw this in, but this is simpler
    540             # to implement for now
--> 541             yield from except_plan(e)
    542         raise
    543     else:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in except_plan(e)
    289             yield from close_run()
    290         else:
--> 291             yield from close_run(exit_status='fail', reason=str(e))
    292 
    293     yield from contingency_wrapper(plan,

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plan_stubs.py in close_run(exit_status, reason)
    731     :func:`bluesky.plans_stubs.open_run`
    732     """
--> 733     return (yield Msg('close_run', exit_status=exit_status, reason=reason))
    734 
    735 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in new_gen()
    807                 yield from ensure_generator(complete_msgs)
    808                 yield from ensure_generator(collect_msgs)
--> 809                 yield msg
    810             return new_gen(), None
    811         else:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in new_gen()
    749             def new_gen():
    750                 yield from ensure_generator(unmonitor_msgs)
--> 751                 yield msg
    752             return new_gen(), None
    753         else:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in post_baseline()
   1105         elif msg.command == 'close_run':
   1106             def post_baseline():
-> 1107                 yield from trigger_and_read(devices, name=name)
   1108                 return (yield msg)
   1109 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plan_stubs.py in trigger_and_read(devices, name)
    800     from .preprocessors import rewindable_wrapper
    801     return (yield from rewindable_wrapper(inner_trigger_and_read(),
--> 802                                           rewindable))
    803 
    804 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in rewindable_wrapper(plan, rewindable)
    647                                             restore_rewindable()))
    648     else:
--> 649         return (yield from plan)
    650 
    651 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plan_stubs.py in inner_trigger_and_read()
    790         if not no_wait:
    791             yield from wait(group=grp)
--> 792         yield from create(name)
    793         ret = {}  # collect and return readings to give plan access to them
    794         for obj in devices:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plan_stubs.py in create(name)
     39     :func:`bluesky.plan_stubs.save`
     40     """
---> 41     return (yield Msg('create', name=name))
     42 
     43 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1195                         # exceptions (coming in via throw) can be
   1196                         # raised
-> 1197                         new_response = yield from coro(msg)
   1198 
   1199                     # special case `CancelledError` and let the outer

/opt/conda_envs/collection-2018-2.0/lib/python3.6/asyncio/coroutines.py in coro(*args, **kw)
    210         @functools.wraps(func)
    211         def coro(*args, **kw):
--> 212             res = func(*args, **kw)
    213             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    214                 isinstance(res, CoroWrapper)):

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _create(self, msg)
   1446                                          "be preceded by 'open_run'.")
   1447         if self._bundling:
-> 1448             raise IllegalMessageSequence("A second 'create' message is not "
   1449                                          "allowed until the current event "
   1450                                          "bundle is closed with a 'save' or "

IllegalMessageSequence: A second 'create' message is not allowed until the current event bundle is closed with a 'save' or dropmessage.

''''

**Comment by tacaswell** [comment]
I believe this is fixed by https://github.com/NSLS-II-SIX/profile_collection/commit/e7b5e0fee3f550a2fb6c27d3336ff606deb3b30d
