### ISSUE TITLE
EpicsSignal is broken

### ISSUE THREAD

**Issue by rixssix** [NSLS-II-SIX/profile_collection#29]
We are using
Versions of DAMA software:

    - Bluesky    : v1.6.0rc4+35.g5350a8e
    - Ophyd      : v1.4.0rc4
    - Databroker : v0.13.3

We are not able to get any "EpicsSignal" definition to work in Bluesky. In particular, these  variables get synchronized only at the start of Bluesky and they do not update later on. The PV's themselves on the other side are active and with caget they return the current values. 
This is clearly a bug from the new version, since we tested everything using the:
Versions of DAMA software:

    - Bluesky    : v1.5.3
    - Ophyd      : v1.3.3.post2+ga207e17
    - Databroker : v0.13.0

And it all works, as it used to.
Please fix the new version asap.

**Comment by tacaswell** [comment]
- Can you clarify what you mean by "We are not able to get any "EpicsSignal" definition to work in Bluesky"?
- When did this stop working?

**Comment by rixssix** [comment]
Hi Tom,
I mean when I define an Epic Signal
m1_pid_fbk = EpicsSignal('XF:02ID-OP{FBTEST2}Sts:FB-Sel', name = 'm1_pid_fbk')

I do not get any update on this value, possibly the one when we restart BS. 
I think this never worked in the new version of BS and ophyd

**Comment by tacaswell** [comment]
> I do not get any update on this value, possibly the one when we restart BS.
I think this never worked in the new version of BS and ophyd

What exactly does this mean?  How are you trying to read the data?

**Comment by rixssix** [comment]
We type:
m1_pid_fbk.value 
in order to get the current value, but it doesn't return the current value we can read from CSS or by directly doing "caget PV..."

**Comment by tacaswell** [comment]
If you do `m1_pid_fbk.read()` does in work?

**Comment by tacaswell** [comment]
and does `m1_pid_pbk.get()` work?

**Comment by rixssix** [comment]
Hi Tom,

Thanks!!
This
m1_pid_pbk.get()
works. Why is the old *.value of the Epics signal not working anymore?
Has something being changed? This is important to know as we have several alignment procedure that rely on these types of definition.

Thanks

**Comment by tacaswell** [comment]
I'm not sure why `.value` is not working, we will have to look into if that was an intentional change.

You should change your code to use `.get()` everywhere because that is a core part of the ophyd API and is guaranteed to continue working and to work on all ophyd objects.

----

In the future please include information like the exact code that is not working, what you expect it to do, what it is doing, and any debugging steps you have tried. 

Please post issues under your own account rather than a shared account.

**Comment by rixssix** [comment]
A possible consequence of the new version, is that the "snap" function doesn't work anymore.
We are using it in this part of code:
def pzshutter_enable():
    rixscam_exp_temp = rixscam.cam.acquire_time.value
    rixscam_exp = 1
    yield from mv(rixscam.cam.acquire_time, rixscam_exp)
    yield from mv(pzshutter,'Detector output')
    yield from snap([rixscam])
    yield from mv(rixscam.cam.acquire_time, rixscam_exp_temp)

Is there a new replacement for it?

**Comment by tacaswell** [comment]
Again, what do you mean "doesn't work"?  

`snap` is a plan from your profile.

https://github.com/NSLS-II-SIX/profile_collection/blob/01190b2ce9cdba65aadd58901c40cda60e0f0dfb/startup/15-valves_and_shutters.py#L115-L145

----

From a very cursory glance at the code you posted, you are again using `.value` again.  Have you tried using `.get()` instead?

You could use stage sigs to set the exposure time (so we manage setting it back) or you can use 

```python
@bps.reset_positions_decorator([rixscam.cam.acquire_time])
def pzshutter_enable():
    yield from mv(rixscam.cam.acquire_time, 1)
    yield from mv(pzshutter,'Detector output')
    yield from snap([rixscam])
```

----

Please do not post under the shared account.
