### ISSUE TITLE
ENH add parameters to configuration_attrs and integrating with PreDefinedPosition class

### ISSUE THREAD

**Issue by ambarb** [NSLS-II-SIX/profile_collection#3]
The motivation for this is related most directly to our pgm, but could be a general thing too. 

We (@bisogni included) would like to have these locations recorded in the configuration attributes instead of the baseline.  In some cases  (like the epics motor calibration offset), this information is already in the configuration_attrs.   We would like to add epics_signals to the configuration_attrs, but do not want to replicated code already used for the `PreDefindedPosition()`.  I'm not sure which is best to go first, taking `configuration_attrs` to building `locations` or vice-versa.  

@awalter-bnl is the `PreDefinedPosition()` going to become a standard for bsui. If so, then maybe we should approach this problem as a way to protoype at 2ID.  Perhaps it is then worth making an enhancment request for bluesky or ophyd.

**Comment by awalter-bnl** [comment]
@ambarb , @Bisogni I am not sure I completely follow what you want, can we meet sometime tomorrow to discuss? I am currently working on a version of PreDefinedPositions to be added to bluesky, so if we need new capabilities now is the time.

**Comment by ambarb** [comment]
after discussion with @awalter-bnl , realized that configuration attributes are only included if the scan has the pgm as the detector or the motor within the scan.  

Better to sort this out completely and finalize once the new ioc for pgm control is implemented.

**Comment by awalter-bnl** [comment]
@ambarb can we close this? or are you keeping it open while we wait on the new PGM ioc?

**Comment by ambarb** [comment]
we can wait until the new ppm ioc is ready.
